### PR TITLE
Avoid infinite recursion

### PR DESCRIPTION
**Pull request by kohsuke**
Counter proposal to https://github.com/jenkinsci/structs-plugin/pull/1

### CODE REVIEW

**Comment by jglick** [comment]
:bee:

**Comment by kwhetstone** [comment]
Some of the code was moved around from when this originally came out.  Will update the new class with these changes.

**Comment by jglick** [comment]
Did the equivalent get applied somewhere?

The [current output](https://jenkins.ci.cloudbees.com/job/infra/job/PipelineStepsDoc/lastSuccessfulBuild/artifact/allAscii.zip) does not seem to include nested objects at all, unless I am missing something.

**Comment by kwhetstone** [comment]
I added in the stack into the documentation generation class.  The nested objects are there just not as obvious due to how asciidoctor is rendering the layers

**Pull request closed without merging**
